### ISSUE TITLE
Release latest changes

### ISSUE THREAD

**Issue by LoicMahieu** [js-data/js-data-sql#11]
Could you please release the latest changes ?
I would like to depend on last commit 5bd32803d9b84021a945cb17ba55ca1fba17f347 but not released yet.
I tried to `npm i --save js-data/js-data-sql@5bd32803d9b84021a945cb17ba55ca1fba17f347` but there are not yet had a build so `dist/js-data-sql.js` is not up to date.

**Comment by jmdobry** [comment]
https://github.com/js-data/js-data-sql/releases/tag/0.5.0
