### ISSUE TITLE
Remove all peerDependencies from package.json

### ISSUE THREAD

**Issue by techniq** [js-data/js-data-sql#15]
My proposal is to remove all db client libraries from `package.json` and require user to install the requested one, and move `js-data` and `knex` as `dependencies`.  I suggest this for the following reasons:

- It's rather odd (and eats up space) to have all the db client libraries installed when performing `npm install js-data-sql`.
- I'm using the `mysql2` driver instead of `mysql` which means I have 2 db client libraries installed for MySQL.
- Knex requires you to install your [desired library](http://knexjs.org/#Installation-node)
- NPM3 will [no longer](http://blog.npmjs.org/post/110924823920/npm-weekly-5) install peer dependencies by default (which is the reason for moving `js-data` and `knex` as true `dependencies`

```
$ npm install --save js-data js-data-sql
npm WARN peerDependencies The peer dependency mariasql@>=0.1.21 included from js-data-sql will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency mysql@>=2.5.5 included from js-data-sql will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency pg@>=4.3.0 included from js-data-sql will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sqlite3@>=3.0.5 included from js-data-sql will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by techniq** [comment]
@jmdobry ping :)

Currenlty I'm unable to `npm install js-data-sql` as I'm using Node v4 which the [mariasql](https://github.com/mscdex/node-mariasql/pull/101) driver is currently broken on (and has no use on my project since I'm using the `mysql2`driver)

**Comment by jmdobry** [comment]
It's your lucky day, I finally got internet at my house today, so the pings mean something.

**Comment by jmdobry** [comment]
@techniq I'm not sure that js-data should be moved from `peerDependencies` to `dependencies`, as this might prevent users from using a particular version of js-data. The npm3 changelog states:

> This [change] shifts the responsibility for fulfilling peer dependencies from library framework / plugin maintainers to application authors

So when you install js-data-sql via npm3, npm3 will warn you if the peerDependency is missing. To fix that, you just add js-data to your own app's package.json file. This would be noted in js-data-sql's changelog.

**Comment by techniq** [comment]
@jmdobry thanks, and glad your back on the grid :)

I'm OK with leaving js-data (and knex) as peerDependencies based on the changelog's explanation. 

Any chance of getting a new version pushed out soon?

**Comment by jmdobry** [comment]
https://github.com/js-data/js-data-sql/releases/tag/0.10.0

**Comment by techniq** [comment]
:+1: thanks

**Comment by techniq** [comment]
@jmdobry Could you push 0.10.0 to npm?

**Comment by jmdobry** [comment]
done
