### ISSUE TITLE
Allow registering custom query operators

### ISSUE THREAD

**Issue by techniq** [js-data/js-data-sql#60]
It would be useful if you could register your own query operator.

```js
var adapter = new DSSqlAdapter({
  client: 'mysql',
  connection: {
    user: 'root'
  },
  queryOperators: {
    'search': (query, field, value) => {
      return query.whereRaw(`MATCH(${query.raw(field)}) AGAINST(? IN BOOLEAN MODE)`, value)
    },
    '|search': (query, field, value) => {
      return query.whereRaw(`MATCH(${query.raw(field)}) AGAINST(? IN BOOLEAN MODE)`, value)
    }
  }
}
```

They should maybe be executed before the built in operators to allow overriding.
https://github.com/js-data/js-data-sql/blob/0.11.9/src/index.js#L350

**Comment by jmdobry** [comment]
> before the built in operators to allow overriding.

You mean after?

**Comment by techniq** [comment]
Probably have to be before/conditionally check if one exists as we wouldn't
want the built in operators to modify the query earlier. On want the
custom/overriden logic for an operator to run (ex '===') or the built in
one.
