### ISSUE TITLE
Upgrading knex from 0.11.5 to 0.12.1 breaks application

### ISSUE THREAD

**Issue by n1ru4l** [js-data/js-data-sql#74]
js-data:2.9.0
js-data-sql: 0.11.17 (using sqlite3 db)

After upgrading knex all test which include findAll-Queries fail with the following error:

```
  1) lib/media-manager importAlbum can import an album:
     TypeError: Expecting a function in instanceof check, but got undefined
      at DSSqlAdapter.filterQuery (node_modules/js-data-sql/dist/js-data-sql.js:415:70)
      at DSSqlAdapter.findAll (node_modules/js-data-sql/dist/js-data-sql.js:336:20)
      at node_modules/js-data/dist/js-data-debug.js:5319:46
```

Code-Example:

``` javascript
const covers = yield Cover.findAll()
```

**Comment by n1ru4l** [comment]
I upgraded to my versions to the following:
js-data: 3.0.0-rc.4
js-data-sql: 1.0.0-beta.3
knex: 0.12.1

After adjusting the codes there seems to be no issue anymore. 

However js-data-sql ist still beta. Are there any information on how long it will take until it becomes stable?

**Comment by jmdobry** [comment]
I'm glad it's working!

As soon as I can get the documentation for 3.x finished up I can release 3.0.0 stable, and release stable versions of the 3.x-compatible adapters.
